repos:
    - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
      rev: v2.0.3
      hooks:
      - id: dbt-compile
      - id: dbt-parse
      - id: dbt-docs-generate
        args: ["--cmd-flags", "++no-compile"]
      - id: generate-model-properties-file
        args: ["--properties-file", "/models/{schema}/{name}.yml", "--"]
      - id: check-script-semicolon
      - id: check-model-has-all-columns
        name: Check columns
        files: ^models/
      - id: check-model-columns-have-desc
        files: ^models/
