version: 2

models:
  - name: src_hosts
    description: "Staging hosts"
    columns:
      - name: host_id
        description: "host id"
        tests:
          - unique
          - not_null
      - name: host_name
        description: "host name"
      - name: is_superhost
        description: "Bool is superhost or not"
        tests:
          - accepted_values:
              values: ['t', 'f', null]
      - name: created_at
        description: "created at"
        tests:
          - not_null
      - name: updated_at
        description: "updated at"
        tests:
          - not_null

  - name: src_listings
    description: "Staging Listings"
    columns:
      - name: listing_id
        description: "listing id"
        tests:
          - unique
          - not_null
      - name: listing_name
        description: "listing name"
        tests:
          - not_null
      - name: listing_url
        description: "listing url"
        tests:
          - not_null
      - name: room_type
        description: "room type"
        tests:
          - not_null
      - name: minimum_nights
        description: "minimum nights"
        tests:
          - not_null
      - name: host_id
        description: "host id"
      - name: price_str
        description: "price in string format"
        tests:
          - not_null
      - name: created_at
        description: "created at"
        tests:
          - not_null
      - name: updated_at
        description: "updated at"
        tests:
          - not_null

  - name: src_reviews
    description: "Staging Reviews"
    columns:
      - name: listing_id
        description: "listing id"
        tests:
          - not_null
      - name: review_date
        description: "review date"
        tests:
          - not_null
      - name: reviewer_name
        description: "reviewer name"
        tests:
          - not_null
      - name: review_text
        description: "reviewer text"
      - name: review_sentiment
        description: "reviewer sentiment"

  - name: dim_listings_cleansed
    description: "Listings cleansed"
    columns:
      - name: listing_id
        description: "listing id"
        tests:
          - unique
          - not_null
      - name: listing_name
        description: "listing name"
        tests:
          - not_null
      - name: room_type
        description: "room type"
        tests:
          - not_null
      - name: minimum_nights
        description: "minimum nights"
        tests:
          - not_null
      - name: host_id
        description: "host id"
      - name: price
        description: "price in float format"
        tests:
          - not_null
      - name: created_at
        description: "created at"
        tests:
          - not_null
      - name: updated_at
        description: "updated at"
        tests:
          - not_null

  - name: dim_hosts_cleansed
    description: "Hosts cleansed"
    columns:
      - name: host_id
        description: "host id"
        tests:
          - relationships:
              to: ref('src_hosts')
              field: host_id
      - name: host_name
        description: "host name"
      - name: is_superhost
        description: "Bool is superhost or not"
        tests:
          - accepted_values:
              values: ['t', 'f', null]
      - name: created_at
        description: "created at"
        tests:
          - not_null
      - name: updated_at
        description: "updated at"
        tests:
          - not_null

  - name: fct_reviews
    description: "Reviews cleansed"
    columns:
      - name: listing_id
        description: "listing id"
        tests:
          - not_null
      - name: review_date
        description: "review date"
        tests:
          - not_null
      - name: reviewer_name
        description: "reviewer name"
        tests:
          - not_null
      - name: review_text
        description: "reviewer text"
      - name: review_sentiment
        description: "reviewer sentiment"

  - name: dim_listings_w_hosts
    description: "Left join table of listings with hosts"
    columns:
      - name: listing_id
        description: "listing id"
        tests:
          - unique
          - not_null
      - name: listing_name
        description: "listing name"
        tests:
          - not_null
      - name: room_type
        description: "room type"
        tests:
          - not_null
      - name: minimum_nights
        description: "minimum nights"
        tests:
          - not_null
      - name: price
        description: "price in float format"
        tests:
          - not_null
      - name: host_id
        description: "host id"
        tests:
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: host_name
        description: "host name"
      - name: host_is_superhost
        description: "Bool is superhost or not"
        tests:
          - accepted_values:
              values: ['t', 'f', null]
      - name: created_at
        description: "created at"
        tests:
          - not_null
      - name: updated_at
        description: "updated at"
        tests:
          - not_null

  - name: mart_fullmoon_reviews
    description: "Mart with reviews and full moon coincidence"
    columns:
      - name: listing_id
        description: "listing id"
        tests:
          - relationships:
              to: ref('fct_reviews')
              field: listing_id
      - name: review_date
        description: "review date"
        tests:
          - not_null
      - name: reviewer_name
        description: "reviewer name"
        tests:
          - not_null
      - name: review_text
        description: "reviewer text"
        tests:
          - not_null
      - name: review_sentiment
        description: "reviewer sentiment"
        tests:
          - not_null
      - name: is_full_moon
        description: "boolean if review is after full moon"
        tests:
          - not_null
